language: java

jdk:
  - openjdk14

sudo: required

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

after_success:
  - ./gradlew jacocoTestReport coveralls

script:
  - export AWS_REGION=travis-test
  - ./gradlew clean build -i --stacktrace

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

